# -*- coding: utf-8 -*-
# Copyright 2022 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the isam_ping module
"""


class PingArgs(object):  # pylint: disable=R0903
    """The arg spec for the isam_ping module
    """

    argument_spec = {
        "ip_address": {"type": "str", "required": True},
        "detail_rapid": {"type": "str"},
        "time_to_live": {"type": "int", "default": 64},
        "type_of_service": {"type": "int", "default": 0},
        "bytes": {"type": "int", "default": 56},
        "pattern": {
            "type": "int",
            "default": "system-generated sequential pattern",
        },
        "centisecs": {"type": "int", "default": 1},
        "secs": {"type": "int", "default": 1},
        "bypass-routing": {"type": "bool", "default": False},
        "requests": {"type": "int", "default": 1},
        "do-not-fragment": {"type": "bool", "default": False},
        "interface-name": {"type": "str"},
        "router-instance": {
            "type": "str",
            "choices": ["Base", "management", "vpls-management"],
        },
        "timeout": {"type": "int", "default": 5},
        "service-name": {"type": "str"},
        "fc-name": {
            "type": "str",
            "choices": ["be", "l2", "af", "l1", "h2", "ef", "h1", "nc"],
            "default": "nc",
        },
    }  # pylint: disable=C0301
