# -*- coding: utf-8 -*-
# Copyright 2022 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the isam_bridges module
"""


class BridgesArgs(object):  # pylint: disable=R0903
    """The arg spec for the isam_bridges module
    """

    argument_spec = {
        "config": {
            "type": "dict",
            "elements": "dict",
            "options": {
                "ageing_time": {"type": "int", "default": 300},
                "port": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "port": {"type": "str"},
                        "pvid": {"type": "int"},
                        "default-priority": {"type": "int"},
                        "mac-learn-off": {"type": "bool"},
                        "max-unicast-mac": {"type": "int"},
                        "qos-profile": {"type": "str"},
                        "prio-regen-prof": {
                            "type": "str",
                            "choices": [
                                "none",
                                "trusted-port",
                                "best-effort",
                                "cl-all-prio-3",
                                "cl-all-prio-4",
                                "background",
                                "be-cl-voice",
                                "be-cl-1d-voice",
                                "be-voice",
                                "l2-vpn-3",
                                "l2-vpn-4",
                                "11",
                                "12",
                                "13",
                                "14",
                                "15",
                                "16",
                                "17",
                                "18",
                                "19",
                                "20",
                                "21",
                                "22",
                                "23",
                                "24",
                                "25",
                                "26",
                                "27",
                                "28",
                                "29",
                                "30",
                                "31",
                                "32",
                            ],
                        },
                        "prio-regen-name": {"type": "str"},
                        "max-commited-mac": {"type": "int"},
                        "mirror-mode": {
                            "type": "str",
                            "choices": ["disable", "overwrite-outer-vlan"],
                        },
                        "mirror-vlan": {"type": "int"},
                        "pvid-tagging-flag": {
                            "type": "str",
                            "choices": ["onu", "olt"],
                        },
                        "ds-pbit-mode": {
                            "type": "str",
                            "choices": ["auto", "translated", "transparency"],
                        },
                        "vlan_id": {
                            "type": "dict",
                            "elements": "dict",
                            "options": {
                                "tag": {
                                    "type": "str",
                                    "choices": [
                                        "untagged",
                                        "single-tagged",
                                        "priority-tagged",
                                    ],
                                },
                                "l2fwder_vlan": {"type": "str"},
                                "vlan_scope": {
                                    "type": "str",
                                    "choices": ["local", "l2fwder", "network"],
                                },
                                "qos": {"type": "str", "default": "none"},
                                "qos_profile": {"type": "str", "default": "none"},
                                "prior_best_effort": {
                                    "type": "boolean",
                                    "default": "none",
                                },
                                "prior_background": {
                                    "type": "boolean",
                                    "default": "none",
                                },
                                "prior_spare": {"type": "boolean"},
                                "prior_exc_effort": {"type": "boolean"},
                                "prior_ctrl_load": {"type": "boolean"},
                                "prior_less_100ms": {"type": "boolean"},
                                "prior_less_10ms": {"type": "boolean"},
                                "prior_nw_ctrl": {"type": "boolean"},
                                "in_qos_prof_name": {"type": "str"},
                                "max_up_qos_policy": {"type": "int"},
                                "max_ip_antispoof": {"type": "int"},
                                "max_unicast_mac": {"type": "int"},
                                "max_ipv6_antispf": {"type": "int"},
                                "mac_learn_ctrl": {"type": "int"},
                                "min_cvlan_id": {"type": "int"},
                                "max_cvlan_id": {"type": "int"},
                                "ds_dedicated_q": {"type": "bool"},
                                "tpid": {"type": "str"},
                            },
                        },
                    },
                },
            },
        },
        "state": {
            "type": "str",
            "choices": ["gathered", "merged", "replaced", "overridden", "deleted"],
            "default": "merged",
        },
    }  # pylint: disable=C0301
