# -*- coding: utf-8 -*-
# Copyright 2022 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the isam_ethernet_ont module
"""


class Ethernet_ontArgs(object):  # pylint: disable=R0903
    """The arg spec for the isam_ethernet_ont module
    """

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "uni_idx": {"type": "str"},
                "port": {
                    "type": "dict",
                    "options": {"pm-collect": {"type": "bool"}},
                },
                "phy": {"type": "dict", "options": {"pm": {"type": "bool"}}},
                "l2": {
                    "type": "dict",
                    "options": {
                        "pm-collect-ext": {
                            "type": "dict",
                            "options": {
                                "pm-collect": {"type": "bool"},
                                "p-bits": {"type": "int"},
                                "vlan-id": {"type": "int"},
                            },
                        },
                        "pm": {"type": "bool"},
                        "tca": {"type": "bool"},
                        "dropped-frames-up": {"type": "bool"},
                        "dropped-frames-dn": {"type": "bool"},
                    },
                },
                "cfm": {
                    "type": "dict",
                    "options": {"portshut-ais": {"type": "bool"}},
                },
                "cust_info": {"type": "str"},
                "auto_detect": {
                    "type": "str",
                    "choices": [
                        "10_100baset-auto",
                        "10baset-fd",
                        "100baset-fd",
                        "1000baset-fd",
                        "auto-basetfd",
                        "10gig-fd",
                        "2.5gig-fd",
                        "5gig-fd",
                        "10baset-auto",
                        "10baset-hd",
                        "100baset-hd",
                        "1000baset-hd",
                        "autobaset-hd",
                        "10_100_1000baset-auto",
                        "100baset-auto",
                        "auto",
                        "1000baset-auto",
                    ],
                },
                "power_control": {"type": "bool"},
                "pse-class": {"type": "int"},
                "pse_pw_priority": {
                    "type": "str",
                    "choices": ["critical", "high", "low"],
                },
                "pwr_override": {"type": "bool"},
                "lpt_mode": {},
                "admin-state": {"type": "bool"},
            },
        },
        "state": {
            "type": "str",
            "choices": ["gathered", "merged", "replaced", "overridden", "deleted"],
            "default": "merged",
        },
    }  # pylint: disable=C0301
