# -*- coding: utf-8 -*-
# Copyright 2022 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the isam_ethernet_line module
"""


class Ethernet_lineArgs(object):  # pylint: disable=R0903
    """The arg spec for the isam_ethernet_line module
    """

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "if_index": {"type": "str", "required": True},
                "port_type": {
                    "type": "str",
                    "choices": ["uni", "nni", "hc-uni", "uplink"],
                },
                "admin_up": {"type": "bool"},
                "tca_line_threshold": {
                    "type": "dict",
                    "options": {
                        "enable": {"type": "bool"},
                        "los": {"type": "int", "default": 0},
                        "fcs": {"type": "int", "default": 0},
                        "rx_octets": {"type": "int", "default": 0},
                        "tx_octets": {"type": "int", "default": 0},
                        "los_day": {"type": "int", "default": 0},
                        "fcs_day": {"type": "int", "default": 0},
                        "rx_octets_day": {"type": "int", "default": 0},
                        "tx_octets_day": {"type": "int", "default": 0},
                    },
                },
                "mau": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "index": {"type": "int"},
                        "mau_type": {
                            "type": "str",
                            "choices": [
                                "10baset",
                                "100basetxhd",
                                "100basetxfd",
                                "100basefxhd",
                                "100basefxhd",
                                "100basefxfd",
                                "1000basexhd",
                                "1000basexfd",
                                "1000baselxhd",
                                "1000baselxfd",
                                "1000basesxhd",
                                "1000basesxfd",
                                "1000basethd",
                                "1000basetfd",
                                "10gbasex",
                                "10gbaser",
                                "10gbaseer",
                                "10gbaselr",
                                "10gbasesr",
                                "100basebx10d",
                                "100basebx10u",
                                "100baselx10",
                                "1000basebx10d",
                                "1000basebx10u",
                                "1000baselx10",
                                "2500basex",
                                "10gbasetfd",
                            ],
                        },
                        "power": {"type": "str", "choices": ["up", "down"]},
                        "speed_auto_sense": {"type": "bool"},
                        "autonegotiate": {"type": "bool"},
                        "cap100base_tfd": {"type": "bool"},
                        "cap1000base_xfd": {"type": "bool"},
                        "cap1000base_tfd": {"type": "bool"},
                    },
                },
            },
        },
        "running_config": {"type": "str"},
        "state": {
            "type": "str",
            "choices": [
                "merged",
                "replaced",
                "overridden",
                "deleted",
                "gathered",
                "rendered",
                "parsed",
            ],
            "default": "merged",
        },
    }  # pylint: disable=C0301
