# -*- coding: utf-8 -*-
# Copyright 2022 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the isam_qos_interface module
"""


class Qos_interfaceArgs(object):  # pylint: disable=R0903
    """The arg spec for the isam_qos_interface module
    """

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "index": {"type": "str"},
                "queue": {"type": "dict"},
                "upstream_queue": {"type": "dict"},
                "ds_rm_queue": {"type": "dict"},
                "scheduler_node": {"type": "str"},
                "ingress_profile": {"type": "str"},
                "cac_profile": {"type": "str"},
                "ext_cac": {"type": "str"},
                "ds_queue_sharing": {"type": "bool"},
                "us_queue_sharing": {"type": "bool"},
                "ds_num_queue": {"type": "bool"},
                "ds_num_rm_queue": {
                    "type": "str",
                    "choices": ["not applicable", "4", "8", "1"],
                },
                "us_num_queue": {
                    "type": "str",
                    "choices": ["not applicable", "4", "8", "1"],
                },
                "queue_stats_on": {"type": "bool"},
                "autoschedule_on": {"type": "bool"},
                "oper_weight": {"type": "int"},
                "oper_rate": {"type": "int"},
                "us_vlanport_queue": {"type": "bool"},
                "dsfld_shaper_prof": {"type": "str"},
                "bandwidth_profile": {"type": "str"},
                "bandwidth_sharing": {
                    "type": "str",
                    "choices": ["no sharing", "ont-sharing"],
                },
                "aggr_usq_profile": {"type": "str"},
                "aggr_dsq_profile": {"type": "str"},
                "gem_sharing": {
                    "type": "str",
                    "choices": ["enable", "disable", "not-applicable"],
                },
                "scheduler_mode": {
                    "choices": [
                        "subscriber-hierarchy",
                        "service-hierarchy",
                        "service-flat",
                    ]
                },
                "mc_scheduler_node": {"type": "str"},
                "bc_scheduler_node": {"type": "str"},
                "ds_schedule_tag": {
                    "type": "str",
                    "choices": ["egressoutertag", "cvlantag", "svlabtag"],
                },
            },
        },
        "state": {
            "type": "str",
            "choices": ["gathered", "merged", "replaced", "overridden", "deleted"],
            "default": "merged",
        },
    }  # pylint: disable=C0301
