# -*- coding: utf-8 -*-
# Copyright 2022 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the isam_ont_slots module
"""


class Ont_slotsArgs(object):  # pylint: disable=R0903
    """The arg spec for the isam_ont_slots module
    """

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "ont_slot_idx": {"type": "str"},
                "planned_card_type": {
                    "type": "str",
                    "required": True,
                    "choices": [
                        "10_100base",
                        "pots",
                        "vdsl2pots",
                        "vdsl2",
                        "ethpots",
                        "video",
                        "veip",
                        "ds1",
                        "e1",
                        "hpna",
                        "moca",
                    ],
                },
                "plndnumdataports": {"type": "int", "required": True},
                "plndnumvoiceports": {"type": "int", "required": True},
                "port-type": {"type": "str", "choices": ["uni", "nni"]},
                "transp-mode-rem": {"type": "bool"},
                "no_mcast_control": {"type": "bool"},
                "admin-state": {"type": "bool"},
            },
        },
        "state": {
            "type": "str",
            "choices": ["gathered", "merged", "replaced", "overridden", "deleted"],
            "default": "merged",
        },
    }  # pylint: disable=C0301
