# -*- coding: utf-8 -*-
# Copyright 2022 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the isam_vlans module
"""


class VlansArgs(object):  # pylint: disable=R0903
    """The arg spec for the isam_vlans module
    """

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "id": {"type": "int"},
                "name": {"type": "str"},
                "mode": {
                    "type": "str",
                    "choices": [
                        "cross-connect",
                        "residential-bridge",
                        "qos-aware",
                        "layer2-terminated",
                        "mirror",
                    ],
                },
                "sntp-proxy": {"type": "bool"},
                "priority": {"type": "int"},
                "vmac-not-in-opt61": {"type": "bool"},
                "new-broadcast:": {
                    "type": "str",
                    "choices": ["inherit", "enable", "disable"],
                    "default": "inherit",
                },
                "protocol-filter": {
                    "type": "str",
                    "choices": [
                        "pass-all",
                        "pass-pppoe",
                        "pass-ipoe",
                        "pass-pppoe-ipoe",
                        "pass-ipv6oe",
                        "pass-pppoe-ipv6oe",
                        "pass-ipoe-ipv6oe",
                        "pass-pppoe-ipoe-ipv6oe",
                    ],
                    "default": "pass-all",
                },
                "pppoe-relay-tag": {
                    "type": "str",
                    "choices": [True, False, "configurable"],
                },
                "drly-srv-usr-side": {"type": "bool", "default": "disable"},
                "new-secure-fwd": {
                    "type": "str",
                    "choices": ["inherit", "enable", "disable"],
                },
                "aging-time": {"type": "int"},
                "l2cp-transparent": {"type": "bool"},
                "in-qos-prof-name": {"type": "str"},
                "ipv4-mcast-ctrl": {"type": "bool"},
                "ipv6-mcast-ctrl": {"type": "bool"},
                "mac-mcast-ctrl": {"type": "bool"},
                "dis-proto-rip": {"type": "bool"},
                "proto-ntp": {"type": "bool"},
                "dis-ip-antispoof": {"type": "bool"},
                "unknown-unicast": {"type": "bool"},
                "pt2ptgem-flooding": {"type": "bool"},
                "mac-movement-ctrl": {"type": "bool"},
                "cvlan4095passthru": {
                    "type": "str",
                    "choices": ["passthru", "not-applicable"],
                },
                "arp-snooping": {"type": "bool"},
                "arp-polling": {"type": "bool"},
                "arp-polling-ip": {"type": "str"},
                "mac-unauth": {"type": "bool"},
            },
        },
        "state": {
            "type": "str",
            "choices": ["merged", "replaced", "overridden", "deleted"],
        },
    }  # pylint: disable=C0301
